services:
  agent:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-agent
    command:
      - "--config=/etc/otel/config.yaml"
    volumes:
      - ./config.yaml:/etc/otel/config.yaml
    networks:
      - otel-network
    restart: always

  dcgm-exporter:
    image: nvidia/dcgm-exporter:latest
    container_name: dcgm-exporter
    runtime: nvidia
    networks:
      - otel-network
    restart: always

networks:
  otel-network:
    name: otel-network
    external: true
